
INSERT INTO USER_DETAILS (user_id, first_name, last_name) VALUES
('USER_NAME1', 'FIRST_NAME_USER1', 'LAST_NAME_USER1'),
('USER_NAME2', 'FIRST_NAME_USER2', 'LAST_NAME_USER2'),
('USER_NAME3', 'FIRST_NAME_USER3', 'LAST_NAME_USER3'),
('USER_NAME4', 'FIRST_NAME_USER4', 'LAST_NAME_USER4');
